name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: he-copy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      PORT: 3001
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Lint & Type Check
        run: pnpm lint && pnpm type-check

      - name: Unit tests with coverage
        run: pnpm test:coverage

      - name: Install Playwright + deps
        run: |
          pnpm exec playwright install --with-deps
          pnpm exec playwright --version

      - name: E2E (Chromium)
        run: pnpm e2e --project=chromium

      - name: E2E (Firefox)
        run: pnpm e2e --project=firefox

      # فعّل WebKit لاحقًا بعد توافر مكتبات النظام
      - name: E2E (WebKit)
        if: false
        run: pnpm e2e --project=webkit

      - name: Build
        run: pnpm build

      - name: Start server & wait for healthcheck
        run: |
          nohup sh -c "PORT=$PORT pnpm start" &
          npx wait-on http://localhost:$PORT/api/health --timeout 60000

      - name: Accessibility
        run: pnpm a11y:ci

      - name: Performance
        run: pnpm perf:ci

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            coverage/**
            playwright-report/**
            test-results/**
            .lighthouseci/**
